#!/usr/bin/expect -f

set timeout -1

spawn telnet localhost 3663

expect "*log(): Connected to FMOD Studio on ::1:3663.*"

send -- "var event = studio.project.lookup(\"event:/Engine\");"
send -- "\r"

expect "*out():*"

send -- "sleep(1000);"
send -- "\r"

expect "*out():*"
send \x1d

